version: '3'

services:
    app:
        image: carlospaezf/teslo-shop:1.0.1
        restart: always
        container_name: teslo-backend
        ports:
            - ${PORT}:${PORT}
        environment:
            APP_VERSION: ${APP_VERSION}
            STAGE: ${STAGE}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_NAME: ${DB_NAME}
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_USERNAME: ${DB_USERNAME}
            PORT: ${PORT}
            HOST_API: ${HOST_API}
            JWT_SECRET: ${JWT_SECRET}
